### ISSUE TITLE
It's burdensome to choose the language for each selection

### ISSUE THREAD

**Issue by EssamWisam** [msris108/codemetry#1]
Thanks for the nice extension.

<img width="495" alt="image" src="https://github.com/msris108/codemetry/assets/49572294/4d61cc96-7a84-4a5d-9b2a-a2ffb13a85fb">

When commenting various sections of a large file, it becomes burdensome to have to choose the same language of the file over and over again. This suggests that `window.activeTextEditor?.document.languageId` gets the targeted opened-file's language (perhaps as usually shown in the bottom). Alternatively, I believe that `gpt-3.5-turbo` could easily figure this out by itself if no language is specified in the prompt.

**Comment by msris108** [comment]
Hi @EssamWisam 

Thanks for the feedback. Do check this out - https://github.com/msris108/codemetry/pull/2 

P.S. Will release the latest version soon

Regards
Sriram M :-)

**Comment by EssamWisam** [comment]
Thanks a lot for the prompt response and PR. The extension definetly deserves far more recognition, well done 👌.
